---
functional:
  - Пользователь должен иметь возможность регистрации через электронную почту, GitHub и Discord
  - Пользователь должен иметь возможность авторизации через электронную почту, GitHub и Discord
  - Пользователь должен иметь возможность создавать игры с ботом
  - Пользователь должен иметь возможность создавать игры с другими игроками
  - Пользователь должен иметь возможность выбирать задачу
  - Пользователь должен иметь возможность просматривать информацию о турнирах
  - Пользователь должен иметь возможность просмотреть личный рейтинг
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть удобным для использования на мобильном устройстве
implicit:
  - Сайт должен иметь расширение для браузера
  - Пользователь может настроить сложность и продолжительность игры

